version: "3.8"

services:
  frontend:
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - "3001:3001"  # Mapeando a porta 3001 no host para a 3000 no container

  backend: 
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 3002:3002
    environment: 
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
